### ISSUE TITLE
auto-updater doesn't work well

### ISSUE THREAD

**Issue by vesper8** [beyondcode/tinkerwell-suggestions#101] opened 2020-02-16 15:33 UTC
the auto-updater is very flaky. Like it will tell me that there's an update available but then it takes a very long time to download the update and doesn't give me any indication that it's downloading it. After 15 minutes it gives me a modal saying the update has been downloaded and it will be installed on next quit. But then I have to quit/re-open multiple times before the new version is used. Overall I would prefer if the update was handled being presented with an 'update found -> install update' button, upon which a modal would show the update being downloaded with progress bar, during which I can't use the application and that's fine with me. And when update is done downloading a button to 'install and relaunch'. It's a lot more clear this way and should hopefully work better too

**Comment by mpociot** [comment] 2020-02-16 15:35
Yeah I know. Seems like that’s the default way how the electron updater works. I’m looking into this

**Comment by matejsvajger** [comment] 2020-03-03 21:46
Same here, I get the notification a new version 2.3 is available, but the update doesn't seem to be downloaded at all. Kept it running now for several hours.

Is there any way I can debug what is happening and provide more useful information?

**Comment by mpociot** [comment] 2020-03-03 23:21
I experienced it again today. What helped for me, once I got the notification that the update would be installed, I quit the app and let it closed for a minute. After reopening it, the update as installed. 
It seems like opening the app too soon doesn’t work

**Comment by xitox97** [comment] 2020-03-05 00:45
I also have this issue on windows 10, update almost half day. nothing happen. Its not even notify me whether the update is complete or not.

**Comment by vesper8** [comment] 2020-03-05 01:06
I just tried following your instructions @mpociot and it didn't work at all. It said an update was available (2.3), I waited until it said the update had been downloaded and would be installed next time I quit. I then quit and waited several hours before re-opening and I was still on 2.2

At this point I find it's much easier and much faster to simply re-download from the website

**Comment by xitox97** [comment] 2020-03-05 05:36
@vesper8 if redownload from the website, do I need to register the license key again? will it used the second quota ? because 1 account can support 2 pc only right?

**Comment by vesper8** [comment] 2020-03-05 18:54
I guess that's a question for @mpociot 

It does ask for the license key on the website, but it didn't ask it again when I ran the app because I assume replacing the old app by the new one this way is the same as using the auto-updater and it should be smart enough to know it's still the same computer. For example my preferences were not lost when I did it this way

**Comment by sschlein** [comment] 2020-03-06 20:05
The app stores the activation on a central local on your system so you can replace it without a new activation. You can also send us a support request to reset your license until we provide a web interface for self-service. We try to do this within hours of your request, depends on the time of the day, etc.

**Comment by matejsvajger** [comment] 2020-03-07 20:30
> I experienced it again today. What helped for me, once I got the notification that the update would be installed, I quit the app and let it closed for a minute. After reopening it, the update as installed.
> It seems like opening the app too soon doesn’t work

Can confirm, not booting app immediately applies the update.

**Comment by NoxxieNl** [comment] 2020-03-11 04:35
> 
> 
> I experienced it again today. What helped for me, once I got the notification that the update would be installed, I quit the app and let it closed for a minute. After reopening it, the update as installed.
> It seems like opening the app too soon doesn’t work

I can confirm also, updated to v2.5.0 today, and after a sloppy 5 minutes of downloading I got the modal, closing and re-opening directly did not update tinkerwell for me, waited a minute or so and it was updated.

It would be nice if it was possible to get a notification that tinkerwell is updating some sort.

**Comment by rockymontana** [comment] 2020-03-12 09:34
Do you see an update progress? I don't see anything. It just says that it exists and that I will be notified when it's updated. But that's it. ATM I just download it manually for each update.
Good job with tinkerwell @mpociot! Really really enjoy it!

**Comment by sschlein** [comment] 2020-03-19 14:47
Starting with 2.6.0 we finally fixed it - so the update after 2.6.0 won't have these issues anymore. Until then, waiting during the update steps or downloading 2.6.0 from the website is the way to go.

**Closed by sschlein** 2020-03-19 14:47 UTC

**Comment by bcorcoran** [comment] 2020-05-13 22:59
I was on 2.6.0 and it was still bad. Can you implement something like what Discord, Atom, or VSCode uses?

**Comment by vesper8** [comment] 2020-05-14 00:03
I can confirm that the problem seemed to have been solved, but the update from 2.6.0 to 2.7.0 was very difficult to obtain

**Comment by mikeerickson** [comment] 2020-05-14 03:47
I am not doing the same here, never worked so I just gave up in general and download the full build for each update (which seems to be slow to download all the time)

**Comment by mikeerickson** [comment] 2020-05-14 03:47
@vesper8 why was this closed if there are so many reports from other users?

**Comment by vesper8** [comment] 2020-05-14 12:27
@mikeerickson well it seemed to be fixed which is why he closed it.. I didn't close it
