### ISSUE TITLE
Fatal error:  Call to undefined function dump() in Psy Shell code

### ISSUE THREAD

**Issue by decadence** [beyondcode/tinkerwell-suggestions#117] opened 2020-02-27 14:55 UTC
I have very basic code:
```php
$user = User::first();
dump($user);
```

which generates "Fatal error:  Call to undefined function dump() in Psy Shell code on line".

`dd` sometimes works sometimes doesn't.
This doesn't work on every local project. But works on default Laravel app.

Feels like file vendor/symfony/var-dumper/Resources/functions/dump.php is not running on the each request.

On the usual web request project works fine.

Tinkerwell Windows 2.2.1

**Comment by decadence** [comment] 2020-03-04 06:01
However VarDumper::dump is working. Don't know why but seems like vendor/symfony/var-dumper/Resources/functions/dump.php is not loaded indeed.

**Comment by sschlein** [comment] 2020-03-06 20:02
I have a hard time reproducing this (works in all my projects). I'm closing the issue until someone finds a way to track this down to something that we can fix. Feel free to reopen this issue with a step-by-step description of how to get this bug.

**Closed by sschlein** 2020-03-06 20:02 UTC

**Comment by decadence** [comment] 2020-03-06 20:26
Don't have a clue about what's wrong so it's easier to use VarDumper::dump instead.

**Comment by wize-wiz** [comment] 2020-04-19 22:43
@decadence Have the same problem, not on all laravel instances but on some of them. I initially wrote a tinkerwell driver. I always used a tinker bootstrap file as in `php artisan tinker tinker`. This would help me make all models and classes I use somewhere available without the need of `use` everywhere.

The tinkerwell driver does the same thing, but sometimes `dump` and `dd` aren't available. 

```php
<?php
// this goes into the apps base_path() . '/.tinkerwell/PreloadTinkerwellDriver.php'
class PreloadTinkerwellDriver extends LaravelTinkerwellDriver {

    /**
     * Variables available in tinkerwell.
     * @var array
     */
    protected $variables = [];

    public function bootstrap($projectPath) {
        parent::bootstrap($projectPath);

        // $projectPath equals `base_path()`.
        $tinker_bootstrap = "{$projectPath}".DIRECTORY_SEPARATOR."tinker";
        if (file_exists($tinker_bootstrap)) {
            require $tinker_bootstrap;
            // make variables available from bootstrap file.
            // $this->variables['whatever_declared_in_bootstrap_file'] = $some_var;
        }
    }

    public function getAvailableVariables() {
        return $this->variables;
    }
}
```

In the root of your app, just create a file `tinker` (with or without `.php` extension, doesn't matter much) and add:

```php
<?php
    // Tinker Bootstrap file
    // this goes into the apps base_path() . 'tinker'
    // @usage: php artisan tinker tinker

    // set sql-query listener to dump all output.
    if(!function_exists('dump')) {
        require base_path().DIRECTORY_SEPARATOR.implode(DIRECTORY_SEPARATOR, ['vendor', 'symfony', 'var-dumper', 'Resources', 'functions', 'dump.php']);
    }
```

Link to [gist](https://gist.github.com/wize-wiz/517ef0f9e8190f407d6c87ede02bba39) to my semi-full bootstrap file for tinker.

Cheers.

**Comment by keithbrink** [comment] 2020-05-02 06:39
I was experiencing this issue, and then from an unrelated issue I found the tip to try changing the PHP binary in Tinkerwell's advanced preferences to /usr/local/bin/php (mine was set to /usr/bin/php). That seems to have resolved this issue as well.

**Comment by shoemoney** [comment] 2020-08-29 15:50
So weird its al ways worked for me until today....

**Comment by gopalkriagg** [comment] 2020-10-14 06:14
It is not working for me either. Laravel 7.

**Comment by gopalkriagg** [comment] 2020-10-14 06:20
Is it because of some unique set of my composer packages?

**Comment by decadence** [comment] 2020-10-14 06:58
@gopalkriagg nobody knows why it's not working sometimes

**Comment by domainoverflow** [comment] 2020-11-29 14:59
Same issue here, i am very disappointed as I was unaware of this tool and saw a mention in laravel news blog. The advertisement is incredible, I had to buy to see it .. Doesn't really work does it ?

**Comment by shoemoney** [comment] 2020-11-29 21:13
My issues have always been related to my settings being wrong until I switched to php8.   I get a strange array error.   Because a lot of others are not complaining I am thinking its still me?

"ErrorException with message 'Undefined array key 314'"

always get that ....

**Comment by domainoverflow** [comment] 2020-12-02 14:02
Hi @sschlein   ... please, as paying customers, would you like to enlighten us ??
